# Exercises - logistic_regression

In [1]:
from sklearn.linear_model import LogisticRegression
#Quiet my warnings for the sake of the lesson:
import warnings
warnings.filterwarnings("ignore")

# Tabular data friends:
import pandas as pd
import numpy as np

# Data viz:
import matplotlib.pyplot as plt
import seaborn as sns

# Sklearn stuff:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, plot_confusion_matrix

# Data acquisition
from pydataset import data
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import numpy as np
import env
import os
import sklearn
from sklearn.metrics import accuracy_score
import acquire
import prepare

In [2]:
df=acquire.get_titanic_data()
df=prepare.prep_titanic(df)
df= df.drop(columns=['Unnamed: 0','passenger_id','embark_town','sex'])
train, validate, test = prepare.split_data(df,'survived')

train -> (534, 9), 59.93%
validate -> (178, 9),19.98%
test -> (179, 9), 20.09%


In [3]:
X_train = train.iloc[:,1:]
y_train = train.survived

X_validate = validate.iloc[:,1:]
y_validate = validate.survived

X_test = test.iloc[:,1:]
y_test = test.survived

### Doing everything with all the Features to set baseline for caomparison

In [4]:
#baseline_prediction = y_train.mode()
# Predict the majority class in the training set
baseline_pred = [0] * len(y_train)
print('Baseline accuracy:', accuracy_score(y_train, baseline_pred))

Baseline accuracy: 0.6161048689138576


In [85]:
# from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()


In [86]:
logit.fit(X_train, y_train)


LogisticRegression()

In [87]:
print(X_train.columns)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)


Index(['pclass', 'age', 'fare', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.15088807e+00 -2.77083109e-02 -1.04544077e-03 -2.59770674e+00]]
Intercept: 
 [4.56711949]


In [88]:
y_pred = logit.predict(X_train)


In [89]:
y_pred_proba = logit.predict_proba(X_train)


In [90]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))


Accuracy of Logistic Regression classifier on training set: 0.80


In [91]:
print(confusion_matrix(y_train, y_pred))


[[277  52]
 [ 55 150]]


In [92]:
print(classification_report(y_train, y_pred))


              precision    recall  f1-score   support

           0       0.83      0.84      0.84       329
           1       0.74      0.73      0.74       205

    accuracy                           0.80       534
   macro avg       0.79      0.79      0.79       534
weighted avg       0.80      0.80      0.80       534



In [93]:
X_train.head()


pclass   age      fare  sex_male
455       3  29.0    7.8958         1
380       1  42.0  227.5250         0
492       1  55.0   30.5000         1
55        1  28.0   35.5000         1
243       3  22.0    7.1250         1

## 1. Create a model that includes only age, fare, and pclass. Does this model perform better than your baseline? no

In [94]:
# get df to only include requiered columns and replace age=nan for median age

df=acquire.get_titanic_data()
df=prepare.prep_titanic2(df)
df=df.drop(columns= ['Unnamed: 0','passenger_id','sex','sibsp','parch','embark_town','alone','sex_male','embark_town_Queenstown','embark_town_Southampton'])
df['age']=df['age'].fillna(df['age'].median())
df.sort_values('age')
train, validate, test = prepare.split_data(df,'survived')

train -> (534, 4), 59.93%
validate -> (178, 4),19.98%
test -> (179, 4), 20.09%


In [95]:
X_train = train.drop(columns='survived')
y_train = train.survived

X_validate = validate.drop(columns='survived')
y_validate = validate.survived

X_test = test.drop(columns='survived')
y_test = test.survived

In [96]:
#baseline_prediction = y_train.mode()
# Predict the majority class in the training set
baseline_pred = [0] * len(y_train)
print('Baseline accuracy:', accuracy_score(y_train, baseline_pred))


Baseline accuracy: 0.6161048689138576


In [97]:
# from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()


In [98]:
logit.fit(X_train, y_train)

LogisticRegression()

In [99]:
print(X_train.columns)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)


Index(['pclass', 'age', 'fare'], dtype='object')
Coefficient: 
 [[-0.92828895 -0.02939958  0.00226961]]
Intercept: 
 [2.42269948]


In [100]:
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)

In [101]:
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))


Accuracy of Logistic Regression classifier on training set: 0.71


In [102]:
print(confusion_matrix(y_train, y_pred))

[[287  42]
 [115  90]]


In [103]:
print(classification_report(y_train, y_pred))


              precision    recall  f1-score   support

           0       0.71      0.87      0.79       329
           1       0.68      0.44      0.53       205

    accuracy                           0.71       534
   macro avg       0.70      0.66      0.66       534
weighted avg       0.70      0.71      0.69       534



## 2. Include sex in your model as well. Note that you'll need to encode or create a dummy variable of this feature before including it in a model. 
Still not better than baseline

In [104]:
df=acquire.get_titanic_data()
df=prepare.prep_titanic2(df)
df=df.drop(columns= ['Unnamed: 0','passenger_id','sex','sibsp','parch','embark_town','alone','embark_town_Queenstown','embark_town_Southampton'])
df['age']=df['age'].fillna(df['age'].median())
df.sort_values('age')
train, validate, test = prepare.split_data(df,'survived')

train -> (534, 5), 59.93%
validate -> (178, 5),19.98%
test -> (179, 5), 20.09%


In [105]:
train.head()

survived  pclass   age      fare  sex_male
455         1       3  29.0    7.8958         1
380         1       1  42.0  227.5250         0
492         0       1  55.0   30.5000         1
55          1       1  28.0   35.5000         1
243         0       3  22.0    7.1250         1

In [106]:
X_train = train.drop(columns='survived')
y_train = train.survived

X_validate = validate.drop(columns='survived')
y_validate = validate.survived

X_test = test.drop(columns='survived')
y_test = test.survived

In [107]:
logit.fit(X_train, y_train)

LogisticRegression()

In [108]:
print(X_train.columns)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)


Index(['pclass', 'age', 'fare', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.15088807e+00 -2.77083109e-02 -1.04544077e-03 -2.59770674e+00]]
Intercept: 
 [4.56711949]


In [109]:
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))


Accuracy of Logistic Regression classifier on training set: 0.80


In [110]:
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

[[277  52]
 [ 55 150]]
              precision    recall  f1-score   support

           0       0.83      0.84      0.84       329
           1       0.74      0.73      0.74       205

    accuracy                           0.80       534
   macro avg       0.79      0.79      0.79       534
weighted avg       0.80      0.80      0.80       534



## 3. Try out other combinations of features and models.

In [113]:
# added parent/child dropped fare
df=acquire.get_titanic_data()
df=prepare.prep_titanic2(df)
df=df.drop(columns= ['Unnamed: 0','passenger_id','fare','sex','sibsp','embark_town','alone','embark_town_Queenstown','embark_town_Southampton'])
df['age']=df['age'].fillna(df['age'].median())
df.sort_values('age')
train, validate, test = prepare.split_data(df,'survived')

train -> (534, 5), 59.93%
validate -> (178, 5),19.98%
test -> (179, 5), 20.09%


In [115]:
X_train = train.drop(columns='survived')
y_train = train.survived

X_validate = validate.drop(columns='survived')
y_validate = validate.survived

X_test = test.drop(columns='survived')
y_test = test.survived


In [116]:
logit.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))


Index(['pclass', 'age', 'parch', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.12724958 -0.0294706  -0.18027688 -2.65960055]]
Intercept: 
 [4.64155507]
Accuracy of Logistic Regression classifier on training set: 0.79


In [117]:
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

[[275  54]
 [ 57 148]]
              precision    recall  f1-score   support

           0       0.83      0.84      0.83       329
           1       0.73      0.72      0.73       205

    accuracy                           0.79       534
   macro avg       0.78      0.78      0.78       534
weighted avg       0.79      0.79      0.79       534



In [ ]:
## only using pclass, age, and sex

In [118]:
df=acquire.get_titanic_data()
df=prepare.prep_titanic2(df)
df=df.drop(columns= ['Unnamed: 0','passenger_id','fare','sex','sibsp','parch','embark_town','alone','embark_town_Queenstown','embark_town_Southampton'])
df['age']=df['age'].fillna(df['age'].median())
df.sort_values('age')
train, validate, test = prepare.split_data(df,'survived')

train -> (534, 4), 59.93%
validate -> (178, 4),19.98%
test -> (179, 4), 20.09%


In [119]:
X_train = train.drop(columns='survived')
y_train = train.survived

X_validate = validate.drop(columns='survived')
y_validate = validate.survived

X_test = test.drop(columns='survived')
y_test = test.survived
#
logit.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))
#
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.11696405 -0.02721983 -2.58979076]]
Intercept: 
 [4.43912502]
Accuracy of Logistic Regression classifier on training set: 0.80
[[283  46]
 [ 60 145]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       329
           1       0.76      0.71      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.79       534
weighted avg       0.80      0.80      0.80       534



## 4. Use you best 3 models to predict and evaluate on your validate sample.

In [ ]:
### evaluate step was done on each model as it was created above
## best model only included age with median age, sex, and passanger class

In [124]:
# make predictions
y_pred1 = logit.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
# accuracy of model 1
print('Accuracy: {:.2f}'.format(logit.score(X_validate, y_validate)))
# confusion matrix of model 1
print(confusion_matrix(y_validate, y_pred1))
# classification report of model 1
print(classification_report(y_validate, y_pred1))

Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.78
[[92 18]
 [21 47]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       110
           1       0.72      0.69      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.77       178
weighted avg       0.78      0.78      0.78       178



## 5. Choose you best model from the validation performation, and evaluate it on the test dataset. How do the performance metrics compare to validate? to train?
my model gage roughly the same results as it did in the train and validate phases. This leades me to assume that the modele is good and not dodeled to closely to the training set.

In [125]:
# make predictions
y_pred1 = logit.predict(X_test)
print("Model 1:only included age with median age, sex, and passanger class")
# accuracy of model 1
print('Accuracy: {:.2f}'.format(logit.score(X_test, y_test)))
# confusion matrix of model 1
print(confusion_matrix(y_test, y_pred1))
# classification report of model 1
print(classification_report(y_test, y_pred1))

Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.80
[[95 15]
 [21 48]]
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       110
           1       0.76      0.70      0.73        69

    accuracy                           0.80       179
   macro avg       0.79      0.78      0.78       179
weighted avg       0.80      0.80      0.80       179



## Bonus1 How do different strategies for handling the missing values in the age column affect model performance?

In [126]:
#### using either mean or median values for null, provided greatter accuracy.
####            However the difference b/w the two was insignificant

## Bonus2: How do different strategies for encoding sex affect model performance?

In [127]:
### not including sex resulted in an accuracy 20% less than if sex in encoded.

# Bonus3: scikit-learn's LogisticRegression classifier is actually applying a regularization penalty to the coefficients by default. 

#### This penalty causes the magnitude of the coefficients in the resulting model to be smaller than they otherwise would be. This value can be modified with the C hyper parameter. Small values of C correspond to a larger penalty, and large values of C correspond to a smaller penalty.
#### Try out the following values for C and note how the coefficients and the model's performance on both the dataset it was trained on and on the validate split are affected.
#### C=.01,.1,1,10,100,1000

In [128]:
df=acquire.get_titanic_data()
df=prepare.prep_titanic2(df)
df=df.drop(columns= ['Unnamed: 0','passenger_id','fare','sex','sibsp','parch','embark_town','alone','embark_town_Queenstown','embark_town_Southampton'])
df['age']=df['age'].fillna(df['age'].median())
df.sort_values('age')
train, validate, test = prepare.split_data(df,'survived')

train -> (534, 4), 59.93%
validate -> (178, 4),19.98%
test -> (179, 4), 20.09%


In [132]:
X_train = train.drop(columns='survived')
y_train = train.survived

X_validate = validate.drop(columns='survived')
y_validate = validate.survived

X_test = test.drop(columns='survived')
y_test = test.survived
#
logit = LogisticRegression()

logit.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit.coef_)
print('Intercept: \n', logit.intercept_)
y_pred = logit.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit.score(X_train, y_train)))
#
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.11696405 -0.02721983 -2.58979076]]
Intercept: 
 [4.43912502]
Accuracy of Logistic Regression classifier on training set: 0.80
[[283  46]
 [ 60 145]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       329
           1       0.76      0.71      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.79       534
weighted avg       0.80      0.80      0.80       534



In [131]:
# make predictions
y_pred1 = logit.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
# accuracy of model 1
print('Accuracy: {:.2f}'.format(logit.score(X_validate, y_validate)))
# confusion matrix of model 1
print(confusion_matrix(y_validate, y_pred1))
# classification report of model 1
print(classification_report(y_validate, y_pred1))

Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.78
[[92 18]
 [21 47]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       110
           1       0.72      0.69      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.77       178
weighted avg       0.78      0.78      0.78       178



In [135]:
# using C=.01
print('Training set with C=.01')
logit2 = LogisticRegression(C=.01)

logit2.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit2.coef_)
print('Intercept: \n', logit2.intercept_)
y_pred = logit2.predict(X_train)
y_pred_proba = logit.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit2.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('-----using validate-----')
y_pred1 = logit2.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
print('Accuracy: {:.2f}'.format(logit2.score(X_validate, y_validate)))
print(confusion_matrix(y_validate, y_pred1))
print(classification_report(y_validate, y_pred1))

Training set with C=.01
Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-0.40124797 -0.01507886 -0.51089056]]
Intercept: 
 [1.21238013]
Accuracy of Logistic Regression classifier on training set: 0.73
[[323   6]
 [140  65]]
              precision    recall  f1-score   support

           0       0.70      0.98      0.82       329
           1       0.92      0.32      0.47       205

    accuracy                           0.73       534
   macro avg       0.81      0.65      0.64       534
weighted avg       0.78      0.73      0.68       534

-----using validate-----
Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.74
[[108   2]
 [ 44  24]]
              precision    recall  f1-score   support

           0       0.71      0.98      0.82       110
           1       0.92      0.35      0.51        68

    accuracy                           0.74       178
   macro avg       0.82      0.67      0.67       178
weighted avg       0.79 

In [136]:
# using C=.1
print('Training set with C=.1')
logit3 = LogisticRegression(C=.1)

logit3.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit3.coef_)
print('Intercept: \n', logit3.intercept_)
y_pred = logit3.predict(X_train)
y_pred_proba = logit3.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit3.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('-----using validate-----')
y_pred1 = logit3.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
print('Accuracy: {:.2f}'.format(logit3.score(X_validate, y_validate)))
print(confusion_matrix(y_validate, y_pred1))
print(classification_report(y_validate, y_pred1))

Training set with C=.1
Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-0.87028232 -0.02311977 -1.78606364]]
Intercept: 
 [3.28588752]
Accuracy of Logistic Regression classifier on training set: 0.80
[[284  45]
 [ 62 143]]
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       329
           1       0.76      0.70      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.78       534
weighted avg       0.80      0.80      0.80       534

-----using validate-----
Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.79
[[96 14]
 [23 45]]
              precision    recall  f1-score   support

           0       0.81      0.87      0.84       110
           1       0.76      0.66      0.71        68

    accuracy                           0.79       178
   macro avg       0.78      0.77      0.77       178
weighted avg       0.79      

In [137]:
# using C=1
print('Training set with C=1')
logit4 = LogisticRegression(C=1)

logit4.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit4.coef_)
print('Intercept: \n', logit4.intercept_)
y_pred = logit4.predict(X_train)
y_pred_proba = logit4.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit4.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('-----using validate-----')
y_pred1 = logit4.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
print('Accuracy: {:.2f}'.format(logit4.score(X_validate, y_validate)))
print(confusion_matrix(y_validate, y_pred1))
print(classification_report(y_validate, y_pred1))

Training set with C=1
Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.11696405 -0.02721983 -2.58979076]]
Intercept: 
 [4.43912502]
Accuracy of Logistic Regression classifier on training set: 0.80
[[283  46]
 [ 60 145]]
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       329
           1       0.76      0.71      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.79       534
weighted avg       0.80      0.80      0.80       534

-----using validate-----
Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.78
[[92 18]
 [21 47]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       110
           1       0.72      0.69      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.77       178
weighted avg       0.78      0

In [138]:
# using C=10
print('Training set with C=10')
logit5 = LogisticRegression(C=10)

logit5.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit5.coef_)
print('Intercept: \n', logit5.intercept_)
y_pred = logit5.predict(X_train)
y_pred_proba = logit5.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit5.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('-----using validate-----')
y_pred1 = logit5.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
print('Accuracy: {:.2f}'.format(logit5.score(X_validate, y_validate)))
print(confusion_matrix(y_validate, y_pred1))
print(classification_report(y_validate, y_pred1))

Training set with C=10
Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.16596829 -0.02803799 -2.73630046]]
Intercept: 
 [4.6595357]
Accuracy of Logistic Regression classifier on training set: 0.80
[[279  50]
 [ 58 147]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       329
           1       0.75      0.72      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.78       534
weighted avg       0.80      0.80      0.80       534

-----using validate-----
Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.78
[[92 18]
 [21 47]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       110
           1       0.72      0.69      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.77       178
weighted avg       0.78      0

In [139]:
# using C=100
print('Training set with C=100')
logit6 = LogisticRegression(C=100)

logit6.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit6.coef_)
print('Intercept: \n', logit6.intercept_)
y_pred = logit6.predict(X_train)
y_pred_proba = logit6.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit6.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('-----using validate-----')
y_pred1 = logit6.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
print('Accuracy: {:.2f}'.format(logit6.score(X_validate, y_validate)))
print(confusion_matrix(y_validate, y_pred1))
print(classification_report(y_validate, y_pred1))

Training set with C=100
Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.17143376 -0.028128   -2.75240908]]
Intercept: 
 [4.68392372]
Accuracy of Logistic Regression classifier on training set: 0.80
[[279  50]
 [ 58 147]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       329
           1       0.75      0.72      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.78       534
weighted avg       0.80      0.80      0.80       534

-----using validate-----
Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.78
[[92 18]
 [21 47]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       110
           1       0.72      0.69      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.77       178
weighted avg       0.78     

In [140]:
# using C=1000
print('Training set with C=1000')
logit7 = LogisticRegression(C=1000)

logit7.fit(X_train, y_train)
print(X_train.columns)
print('Coefficient: \n', logit7.coef_)
print('Intercept: \n', logit7.intercept_)
y_pred = logit7.predict(X_train)
y_pred_proba = logit7.predict_proba(X_train)
print('Accuracy of Logistic Regression classifier on training set: {:.2f}'
     .format(logit7.score(X_train, y_train)))
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))
print('-----using validate-----')
y_pred1 = logit7.predict(X_validate)
print("Model 1:only included age with median age, sex, and passanger class")
print('Accuracy: {:.2f}'.format(logit7.score(X_validate, y_validate)))
print(confusion_matrix(y_validate, y_pred1))
print(classification_report(y_validate, y_pred1))

Training set with C=1000
Index(['pclass', 'age', 'sex_male'], dtype='object')
Coefficient: 
 [[-1.17199494 -0.02813754 -2.75403922]]
Intercept: 
 [4.68642204]
Accuracy of Logistic Regression classifier on training set: 0.80
[[279  50]
 [ 58 147]]
              precision    recall  f1-score   support

           0       0.83      0.85      0.84       329
           1       0.75      0.72      0.73       205

    accuracy                           0.80       534
   macro avg       0.79      0.78      0.78       534
weighted avg       0.80      0.80      0.80       534

-----using validate-----
Model 1:only included age with median age, sex, and passanger class
Accuracy: 0.78
[[92 18]
 [21 47]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       110
           1       0.72      0.69      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.77       178
weighted avg       0.78    