# Exercises - random_forests

## 1. Fit the Random Forest classifier to your training sample and transform (i.e. make predictions on the training sample) setting the random_state accordingly and setting min_samples_leaf = 1 and max_depth = 10.

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import numpy as np
import env
import os
import sklearn
import acquire
import prepare
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [6]:
#  get and prep titanic
df= acquire.get_titanic_data()
df=prepare.prep_titanic(df)

In [7]:
df=df.drop(columns=['Unnamed: 0','passenger_id','embark_town','sex'])

In [8]:
train, validate, test =prepare.split_data(df,'survived')

train -> (534, 9), 59.93%
validate -> (178, 9),19.98%
test -> (179, 9), 20.09%


/Users/ScottBarnett/codeup-data-science/classification-exercises/prepare.py:61: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  train_validate, test = train_test_split(df, test_size=.2, random_state=123, stratify=df[{strat}])
/Users/ScottBarnett/codeup-data-science/classification-exercises/prepare.py:65: FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.
  stratify=train_validate[{strat}])


In [9]:
train.head()


survived  pclass  sibsp  parch      fare  alone  sex_male  \
455         1       3      0      0    7.8958      1         1   
380         1       1      0      0  227.5250      1         0   
492         0       1      0      0   30.5000      1         1   
55          1       1      0      0   35.5000      1         1   
243         0       3      0      0    7.1250      1         1   

     embark_town_Queenstown  embark_town_Southampton  
455                       0                        0  
380                       0                        0  
492                       0                        1  
55                        0                        1  
243                       0                        1

In [11]:
train.survived.value_counts()

0    329
1    205
Name: survived, dtype: int64

In [12]:
#What is your baseline prediction? survived = 0 
#calculate baseline accuracy
baseline_accuracy = 329 / (329+205)
baseline_accuracy

0.6161048689138576

In [13]:
#set target
target = 'survived'

In [14]:
#nset target to y_train
y_train = train[target]
y_train.head()

455    1
380    1
492    0
55     1
243    0
Name: survived, dtype: int64

In [15]:
#repeat for validate and test
y_validate = validate[target]
y_test = test[target]

In [16]:
#set all my features as my X_train
X_train = train.iloc[:,1:]
X_train.head()

pclass  sibsp  parch      fare  alone  sex_male  embark_town_Queenstown  \
455       3      0      0    7.8958      1         1                       0   
380       1      0      0  227.5250      1         0                       0   
492       1      0      0   30.5000      1         1                       0   
55        1      0      0   35.5000      1         1                       0   
243       3      0      0    7.1250      1         1                       0   

     embark_town_Southampton  
455                        0  
380                        0  
492                        1  
55                         1  
243                        1

In [17]:
#repeat for validate and test
X_validate = validate.iloc[:,1:]
X_test = test.iloc[:,1:]

In [37]:
#make the object

forest = RandomForestClassifier(max_depth = 10,min_samples_leaf=1)
forest

RandomForestClassifier(max_depth=10)

In [38]:
#Fit in object
#building our model on our train values
forest.fit(X_train, y_train)

RandomForestClassifier(max_depth=10)

In [39]:
#Transform the object
#score on my train data
forest.score(X_train, y_train)

0.9438202247191011

In [40]:
forest.score(X_validate, y_validate)

0.7640449438202247

## 2. Evaluate your results using the model score, confusion matrix, and classification report.

In [41]:
print(forest.feature_importances_)


[0.10864076 0.06418704 0.05223846 0.38524128 0.02458927 0.31117126
 0.0168595  0.03707244]


In [43]:
y_pred = forest.predict(X_train)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [45]:
y_pred_proba = forest.predict_proba(X_train)
y_pred_proba

array([[7.99035105e-01, 2.00964895e-01],
       [8.33333333e-04, 9.99166667e-01],
       [5.19691477e-01, 4.80308523e-01],
       ...,
       [8.81375280e-01, 1.18624720e-01],
       [9.47478064e-01, 5.25219362e-02],
       [0.00000000e+00, 1.00000000e+00]])

In [46]:
print('Accuracy of random forest classifier on training set: {:.2f}'
     .format(forest.score(X_train, y_train)))


Accuracy of random forest classifier on training set: 0.94


In [47]:
print(confusion_matrix(y_train, y_pred))


[[325   4]
 [ 26 179]]


In [50]:
#find labels in our dataset & sort
labels = sorted(y_train.astype(str).unique())
labels

['0', '1']

In [51]:
pd.DataFrame(confusion_matrix(y_train, y_pred),
            index=[label + '_actual'for label in labels],
            columns=[label + '_predict'for label in labels])

0_predict  1_predict
0_actual        325          4
1_actual         26        179

In [48]:
print(classification_report(y_train, y_pred))


              precision    recall  f1-score   support

           0       0.93      0.99      0.96       329
           1       0.98      0.87      0.92       205

    accuracy                           0.94       534
   macro avg       0.95      0.93      0.94       534
weighted avg       0.95      0.94      0.94       534



## 3. Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.